//kill_line.c
//kill ViewOverall with a bug or ViewOverall that you want to ignore.

//the format of data files must be
//	View_Overall# Iteration DAQ-X Pulse_Amp Field #DWs
//	and the first line of the files must be column names above

//the numbers of data files are all recgnized as real numbers, not integer 	
//Input file must always be the original file, not .kill file.
//Output file is .kill without specified ViewOverall

//You can use this program to delete specified lines of output files generated by dis_magne.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char** argv) {
	FILE *fp_in, *fp_temp;
	char *InputFileName;
	char TempFileName[200];
	char OutputFileName[200];

	double data[6];
	double kill_VOA;
	double VOA_previous = 0.0;
	int Mode;
	char command_mv[300];
	char command_rm[300];

	char dust[8][100];	//for non-substitution fscanf

	if (argc != 4) {
		fprintf(stderr, "Usage: %s InputFileName Mode kill_ViewOverall\n", argv[0]);
		fprintf(stderr, "Mode 1: InputFile is original file that you have not deleted any lines with this program.\n");
		fprintf(stderr, "Mode 2: InputFile is .kill file that you have already deleted one or more lines with this program.\n");
		return -10;
	}
	InputFileName = argv[1];
	Mode = atoi(argv[2]);
	kill_VOA = atof(argv[3]);

	sprintf(OutputFileName, "%s.kill", InputFileName);
	sprintf(TempFileName, "%s.temp", OutputFileName);

	if (Mode == 1) {
		if ((fp_in = fopen(InputFileName, "r")) == NULL) {
			fprintf(stderr, "Can't open file %s\n", InputFileName);
			return -20;
		}
	} else if (Mode == 2) {
		if ((fp_in = fopen(OutputFileName, "r")) == NULL) {
			fprintf(stderr, "Can't open file %s\n", OutputFileName);
			return -20;
		}
	} else {
		fprintf(stderr, "You specified incorrect Mode. Mode is 1 or 2.\n");
		return -50;
	}

	if ((fp_temp = fopen(TempFileName, "w")) == NULL) {
		fprintf(stderr, "Can't open file %s\n", TempFileName);
		return -70;
	}


	fscanf(fp_in, "%s %s %s %s %s %s %s %s\n", dust[0], dust[1], dust[2], dust[3], dust[4], dust[5], dust[6], dust[7]);
	fprintf(fp_temp, "%s %s %s %s %s %s %s %s\n", dust[0], dust[1], dust[2], dust[3], dust[4], dust[5], dust[6], dust[7]);

	while (fscanf(fp_in, "%lf %lf %lf %lf %lf %lf\n", &data[0], &data[1], &data[2], &data[3], &data[4], &data[5]) != EOF) {
		if ((data[0] > (kill_VOA - 0.1)) && (data[0] < (kill_VOA + 0.1))) {
		} else if (data[0] > (VOA_previous - 0.1)) {	// if data[0] < VOA_previous, it is a bug
			fprintf(fp_temp, "%lf %lf %lf %lf %lf %lf\n", data[0], data[1], data[2], data[3], data[4], data[5]);
			VOA_previous = data[0];
		}
	}

	fclose(fp_in);
	fclose(fp_temp);
	if (Mode == 2) { 
		// rm InputFileName
		sprintf(command_rm, "rm %s", OutputFileName);
		if (system(command_rm) == -1) fprintf(stderr, "Can't execute command_rm\n");
	}
	// mv TempFileName OutputFileName
	sprintf(command_mv, "mv %s %s", TempFileName, OutputFileName);
	if (system(command_mv) == -1) fprintf(stderr, "Can't execute command_mv\n");

	return 0;
}





